[tool.isort]
line_length = 88
force_single_line = true

[tool.flake8]
max_line_length = 89

[tool.check-manifest]
ignore = [".*", "mutmut_config.py", "test-requirements.txt", "tox.ini", "examples/*"]
[tool.pyright]
include = ["fastkml"]
exclude = ["**/node_modules",
    "**/__pycache__",
    ".pytype",
    ".pyre",
    "fastkml/test_main.py"
]
